AWSTemplateFormatVersion: '2010-09-09'

Resources:

  AppEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: kt-nginx

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: kt-account1-cluster

  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: kt-account1-nginx-task
      RequiresCompatibilities: [ FARGATE ]
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !ImportValue "kt-EcsTaskExecutionRoleArn"
      ContainerDefinitions:
        - Name: nginx-container
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/kt-nginx:v8"
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue "kt-EcsLogGroupName"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  EcsService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: kt-account1-nginx-service
      Cluster: !Ref EcsCluster
      TaskDefinition: !Ref EcsTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 0
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue "kt-PrivateSubnet1aId"
          SecurityGroups:
            - !ImportValue "kt-EcsSecurityGroupId"