AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EcsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/kt-account1-nginx
      RetentionInDays: 7

Outputs:
  EcsLogGroupName:
    Value: !Ref EcsLogGroup
    Export:
      Name: "kt-EcsLogGroupName"