AWSTemplateFormatVersion: '2010-09-09'

Resources:

  GitHubActionsLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'miyazato-kt1-github-actions-logs-${AWS::AccountId}-${AWS::Region}'

      ObjectLockEnabled: true

      VersioningConfiguration:
        Status: Enabled

      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Mode: GOVERNANCE
            Days: 30

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogsAndVersionsRule
            Status: Enabled
            ExpirationInDays: 90
            NoncurrentVersionExpiration:
              NoncurrentDays: 90

      Tags:
        - Key: Name
          Value: GitHubActions-Execution-Logs
        - Key: Environment
          Value: kt1

Outputs:

  GitHubActionsLogBucketName:
    Value: !Ref GitHubActionsLogBucket
    Export:
      Name: "miyazato-kt1-GitHubActionsLogBucketName"